---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: budaiscaler-manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: budaiscaler-manager-role
subjects:
  - kind: ServiceAccount
    name: budaiscaler-controller-manager
    namespace: budaiscaler-system
