{{- if .Values.metrics.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "scaler.fullname" . }}-metrics
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "scaler.labels" . | nindent 4 }}
spec:
  type: {{ .Values.metrics.service.type }}
  ports:
    - port: {{ .Values.metrics.service.port }}
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    {{- include "scaler.selectorLabels" . | nindent 4 }}
{{- end }}
